name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Running on a self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -vvv -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" << 'EOF'
          cd /home/devops_trainee/test/simple-reactjs-app
          mv docker-compose.yml docker-compose.old.yml
          mv Dockerfile Dockerfile.old
          git pull origin master
          mv docker-compose.old.yml docker-compose.yml
          mv Dockerfile.old Dockerfile
          docker-compose up --build -d
          EOF

